In [3]:
from __future__ import print_function

import string
import random
import pickle
import sys
import os
import time

import numpy as np
# import theano
# import theano.tensor as T

sys.setrecursionlimit(10000)

import _pickle

def unpickle(file):
    fo = open(file, 'rb')
    dict = _pickle.load(fo,encoding='iso-8859-1')
    fo.close()
    return dict

def load_data():
    X = []
    Y = []
    for j in range(5):
        d = unpickle('cifar-10-batches-py/data_batch_'+str(j+1))
        xt = d['data']
        y_train1 = d['labels']
        X.append(xt)
        Y.append(y_train1)

        xt = np.concatenate(X)
        y_train1 = np.concatenate(Y).astype(np.int32)

        d = unpickle('cifar-10-batches-py/test_batch')
        x_test = d['data']
        y_test = np.array(d['labels'],dtype=np.int32)

        X_t = np.reshape(xt, (xt.shape[0], -1))
        X_test = np.reshape(x_test, (x_test.shape[0], -1))


        # add bias dimension and transform into columns
        X_t = np.hstack([X_t, np.ones((X_t.shape[0], 1))])
        X_test = np.hstack([X_test, np.ones((X_test.shape[0], 1))])
       
    return X_t, y_train1, X_test, y_test

load_data()

(array([[  59.,   43.,   50., ...,   84.,   72.,    1.],
        [ 154.,  126.,  105., ...,  142.,  144.,    1.],
        [ 255.,  253.,  253., ...,   83.,   84.,    1.],
        ..., 
        [  35.,   40.,   42., ...,   66.,   50.,    1.],
        [ 189.,  186.,  185., ...,  171.,  171.,    1.],
        [ 229.,  236.,  234., ...,  162.,  161.,    1.]]),
 array([6, 9, 9, ..., 9, 1, 1]),
 array([[ 158.,  159.,  165., ...,  129.,  110.,    1.],
        [ 235.,  231.,  232., ...,  191.,  199.,    1.],
        [ 158.,  158.,  139., ...,    3.,    7.,    1.],
        ..., 
        [  20.,   19.,   15., ...,   53.,   47.,    1.],
        [  25.,   15.,   23., ...,   81.,   80.,    1.],
        [  73.,   98.,   99., ...,   58.,   26.,    1.]]),
 array([3, 8, 8, ..., 5, 1, 7]))

In [4]:
    X = []
    Y = []
    for j in range(5):
        d = unpickle('cifar-10-batches-py/data_batch_'+str(j+1))
        xt = d['data']
        y_train1 = d['labels']
        X.append(xt)
        Y.append(y_train1)

        xt = np.concatenate(X)
        y_train1 = np.concatenate(Y).astype(np.int32)

        d = unpickle('cifar-10-batches-py/test_batch')
        x_test = d['data']
        y_test = np.array(d['labels'],dtype=np.int32)

        X_t = np.reshape(xt, (xt.shape[0], -1))
        X_test = np.reshape(x_test, (x_test.shape[0], -1))


        # add bias dimension and transform into columns
        X_t = np.hstack([X_t, np.ones((X_t.shape[0], 1))])
        X_test = np.hstack([X_test, np.ones((X_test.shape[0], 1))])

In [18]:
X_t.shape

(50000, 3073)

In [11]:
y_train1.shape

(50000,)

In [20]:
X_test.shape

(10000, 3073)

In [13]:
y_test.shape

(10000,)

In [5]:
from sklearn import cross_validation

X_train, X_val, y_train, y_val = cross_validation.train_test_split(X_t, y_train1, test_size=0.2)

In [27]:
X_train.shape

(40000, 3073)

In [35]:
X_val.shape

(10000, 3073)

In [36]:
y_train.shape

(40000,)

In [6]:
D = 3073 # dimensionality
K = 10 # number of classes

In [7]:
W = 0.01 * np.random.randn(D,K)
b = np.zeros((1,K))

In [10]:
# Initial values from hyperparameter
reg = 1e-3 # regularization strength

step_size = 1e-0

# Xtt=X_train[:20000,:]
# ytt=y_train1[:20000,:]
#Xtt=X_train[20001:40000,:]
#ytt=y_train[20001:40000,:]

Xtt=X_train[:1000,:]
ytt=y_train[:1000,]
num_examples = Xtt.shape[0]
# gradient descent loop

In [12]:
for i in range(100):
  
    # evaluate class scores, [N x K]
    scores = (np.dot(Xtt, W) + b )
  
    # compute the class probabilities
    exp_scores = np.exp(scores)
    probs = (exp_scores / np.sum(exp_scores, axis=1, keepdims=True))/1000 # [N x K]

  
#     # compute the loss: average cross-entropy loss and regularization
    corect_logprobs = -np.log(probs[range(num_examples),ytt])
#     corect_logprobs = -np.log(probs[np.random.randint(0,X_train.shape[0],num_examples),y_train1])
    data_loss = np.sum(corect_logprobs)/num_examples
    reg_loss = 0.5*reg*np.sum(W*W)
    loss = data_loss + reg_loss
    
    if i % 10 == 0:
        print("iteration:",i, " loss:",loss)
       
  
#     # compute the gradient on scores
    dscores = probs
    dscores[range(num_examples),ytt] -= 1
    dscores /= num_examples
  
    # backpropate the gradient to the parameters (W,b)
    dW = np.dot(Xtt.T, dscores)
    db = np.sum(dscores, axis=0, keepdims=True)
  
    dW += reg*W # regularization gradient
  
    # perform a parameter update
    W += -step_size * dW
    b += -step_size * db

iteration: 0  loss: nan
iteration: 10  loss: nan
iteration: 20  loss: nan
iteration: 30  loss: nan
iteration: 40  loss: nan
iteration: 50  loss: nan
iteration: 60  loss: nan
iteration: 70  loss: nan
iteration: 80  loss: nan
iteration: 90  loss: nan
